### PR TITLE
Glide

### PR DESCRIPTION
**Pull request by kitplummer**
Switching to Glide, which is being adopted by the customer as a de facto standard for Go package management.  This also allows us to work with Seb's Glide dependency analysis stuff once integrated.

No functional changes, just cleared out the vendor dir, requiring Glide to be installed and run to populate the vendor directory based on version definitions.

### CODE REVIEW

**Comment by matthewkmayer** [comment]
Are we no longer vendoring dependencies?

**Comment by kitplummer** [comment]
Dependencies are installed by Glide now.

**Comment by matthewkmayer** [comment]
Does this leave us vulnerable to a leftpad scenario?

**Comment by kitplummer** [comment]
Vulnerable to a build breaking yes.  But, at least we'd know the dependency was no longer available.

**Comment by matthewkmayer** [comment]
👍

**Pull request merged**
